---
# =================================================================================================
# Area labels - Pull Requests
# =================================================================================================
- name: area/github
  color: "000000" # github black
  description: Changes made in the github directory

# =================================================================================================
# Size Labels
# =================================================================================================
- name: size/XS
  color: "0000ff"
- name: size/S
  color: "000ff0"
- name: size/M
  color: "00ff00"
- name: size/L
  color: "0ff000"
- name: size/XL
  color: "ff0000"
- name: size/XXL
  color: "ff00ff"

# =================================================================================================
# Issue Types
# =================================================================================================
- name: issue/bug
  color: "ff0000"
- name: issue/feature
  color: "00ff00"
- name: issue/chore
  color: "0000ff"
