---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: ./.github/workflows/reusable-labeler.yaml
    secrets: inherit
    with:
      config-file: .github/configs/labeler.yaml
