---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry Run"
        default: true
        required: false
        type: boolean

  # Scheduled daily
  schedule:
    - cron: "0 0 * * *"

  pull_request:
    paths:
      - ".github/workflows/git-release-semver.yaml"
      - ".github/workflows/reusable-**"
      - ".github/configs/release.config.mjs"

jobs:
  release:
    uses: ./.github/workflows/reusable-release-semver.yaml
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
      config-file: ./.github/configs/release.config.mjs
