---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Markdown Lint

on:
  workflow_call:
    inputs:
      version:
        description: The version of markdownlint-cli to install
        type: string
        required: false
        default: latest
      config-file:
        description: Path to the markdownlint config file (optional)
        type: string
        required: false
        default: ""
      extra-flags:
        description: Additional CLI flags for markdownlint
        type: string
        required: false
        default: "--dot"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-markdownlint:${{ inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run MarkdownLint
        shell: bash
        run: |
          set -xe
          read -ra ARGS <<< "${{ inputs.extra-flags }}"

          if [[ -n "${{ inputs.config-file }}" ]]; then
            echo "Using provided config file: ${{ inputs.config-file }}"
            ARGS+=("--config=${{ inputs.config-file }}")
          else
            echo "Using no configuration file."
          fi

          # Execute command with all arguments
          markdownlint "**/*.md" "${ARGS[@]}"
