---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - CommitLint

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use
        type: string
        required: false
        default: lts/*
      commitlint-version:
        description: The version of @commitlint/cli to install
        type: string
        required: false
        default: latest
      conventional-config-version:
        description: The version of @commitlint/config-conventional to install
        type: string
        required: false
        default: latest
      config-file:
        description: Path to the commitlint config file (optional)
        type: string
        required: false
        default: ""
      extra-flags:
        description: Additional CLI flags for commitlint
        type: string
        required: false
        default: "--color --verbose"

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install CommitLint
        run: |
          npm install -g \
            @commitlint/cli@${{ inputs.commitlint-version }} \
            @commitlint/config-conventional@${{ inputs.conventional-config-version }}
          npm list -g --depth=0

      - name: Validate PR commits with CommitLint
        if: github.event_name == 'pull_request'
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          set -xe
          read -ra ARGS <<< "${{ inputs.extra-flags }}"

          if [[ -n "${{ inputs.config-file }}" ]]; then
            echo "Using provided config file: ${{ inputs.config-file }}"
            ARGS+=("--extends=${{ inputs.config-file }}")
          else
            echo "Using no configuration file."
          fi

          # Execute command with all arguments
          echo "$TITLE" | npx commitlint "${ARGS[@]}"
