---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - CommitLint

on:
  workflow_call:
    inputs:
      version:
        description: The version of @commitlint/cli to install
        type: string
        required: false
        default: latest
      conventional-config-version:
        description: The version of @commitlint/config-conventional to install
        type: string
        required: false
        default: latest
      config-file:
        description: Path to the commitlint config file (optional)
        type: string
        required: false
        default: ""
      extra-flags:
        description: Additional CLI flags for commitlint
        type: string
        required: false
        default: "--color --verbose"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-commitlint:${{ inputs.version }}
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate PR commits with CommitLint
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          set -xe
          read -ra ARGS <<< "${{ inputs.extra-flags }}"

          if [[ -n "${{ inputs.config-file }}" ]]; then
            echo "Using provided config file: ${{ inputs.config-file }}"
            ARGS+=("--extends=${{ inputs.config-file }}")
          else
            echo "Using no configuration file."
          fi

          # Execute command with all arguments
          echo "$TITLE" | npx commitlint "${ARGS[@]}"
