---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Go Test

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: The Go version to use.
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Run Tests
        run: go test -v ./... -race -covermode=atomic
