---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Renovate

on:
  workflow_call:
    secrets:
      BOT_APP_ID:
        required: true
      BOT_APP_PRIVATE_KEY:
        required: true
    inputs:
      version:
        description: The version of renovate to install
        type: string
        required: false
        default: latest
      config-file:
        description: Path to the renovate config file
        type: string
        required: true
      dry-run:
        description: Dry Run
        type: boolean
        required: false
        default: false
      log-level:
        description: Log Level
        type: string
        required: false
        default: debug
      extra-flags:
        description: Additional CLI flags for renovate
        type: string
        required: false
        default: ""

env:
  # https://docs.renovatebot.com/self-hosted-configuration/
  LOG_LEVEL: "${{ inputs.log-level }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dry-run == true }}"
  RENOVATE_ONBOARDING: false
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_GIT_AUTHOR: "mr-borboto[bot] <170036086+mr-borboto[bot]@users.noreply.github.com>"
  RENOVATE_CONFIG_FILE: "${{ inputs.config-file }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:${{ inputs.version }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: npx renovate ${{ inputs.extra-flags }}
