---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Renovate

on:
  # from other repositories
  workflow_call:
    inputs:
      config-file:
        description: Path to the renovate config file
        required: true
        type: string
      dry-run:
        type: boolean
        description: Dry Run
        default: false
        required: false
      log-level:
        type: string
        description: Log Level
        default: debug
        required: false

env:
  # https://docs.renovatebot.com/self-hosted-configuration/
  LOG_LEVEL: "${{ inputs.log-level || 'debug' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dry-run == true }}"
  RENOVATE_ONBOARDING: false
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_GIT_AUTHOR: "mr-borboto[bot] <170036086+mr-borboto[bot]@users.noreply.github.com>"
  RENOVATE_CONFIG_FILE: "${{ inputs.config-file }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:20

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Install Renovate
        run: |
          npm install -g renovate
          npm list --depth=0

      - name: Renovate
        run: npx renovate
        env:
          RENOVATE_TOKEN: "${{ steps.app-token.outputs.token }}"
