# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - YAMLLint

on:
  workflow_call:
    inputs:
      python-version:
        description: The version of Python to use
        type: string
        required: false
        default: "3.12"
      yamllint-version:
        description: The version of yamllint to install
        type: string
        required: false
        default: latest
      config-file:
        description: Path to the yamllint config file
        type: string
        required: false
        default: .yamllint.yaml
      extra-flags:
        description: Additional CLI flags for yamllint
        type: string
        required: false
        default: ""

jobs:
  yamllint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install yamllint
        run: |
          if [ "${{ inputs.yamllint-version }}" = "latest" ]; then
            pip install yamllint
          else
            pip install yamllint==${{ inputs.yamllint-version }}
          fi
          pip list

      - name: Run yamllint
        run: yamllint --config-file ${{ inputs.config-file }} ${{ inputs.extra-flags }} .
