---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - YAMLlint

on:
  workflow_call:
    inputs:
      version:
        description: The version of yamllint to use.
        type: string
        required: false
        default: latest
      config-file:
        description: Path to the yamllint config file (optional)
        type: string
        required: false
        default: ""
      extra-flags:
        description: Additional CLI flags for yamllint
        type: string
        required: false
        default: ""

jobs:
  yamllint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-yamllint:${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run yamllint
        shell: bash
        run: |
          set -xe
          read -ra ARGS <<< "${{ inputs.extra-flags }}"

          if [[ -n "${{ inputs.config-file }}" ]]; then
            echo "Using provided config file: ${{ inputs.config-file }}"
            ARGS+=("--config-file" "${{ inputs.config-file }}")
          else
            echo "Using no configuration file."
          fi

          # Execute command with all arguments
          yamllint "${ARGS[@]}" .
