---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Terraform FMT

on:
  workflow_call:
    inputs:
      terraform-version:
        type: string
        description: The Terraform version to use.
        required: false
        default: "1.10.5" #! TODO: renovate annotation

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform fmt
        shell: bash
        run: terraform fmt -recursive -check
