# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Go Test

on:
  workflow_call:
    inputs:
      go-version:
        description: The version of golang to use
        type: string
        required: false
        default: stable
      extra-flags:
        description: Additional CLI flags for go test
        type: string
        required: false
        default: "-race -covermode=atomic"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Tests
        run: go test -v ./... ${{ inputs.extra-flags }}
