---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - YAMLLint

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory to lint"
        type: string
        required: false
        default: "."
      config-file:
        description: "Path to the yamllint config file"
        type: string
        required: false
        default: ".yamllint.yaml"
      extra-flags:
        description: "Additional CLI flags for yamllint"
        type: string
        required: false
        default: ""

jobs:
  yamllint:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/python:3.12

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        working-directory: ${{ inputs.working-directory }}
        run: yamllint --config-file ${{ inputs.config-file }} ${{ inputs.extra-flags }} .
