---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable - Docker Build Push

on:
  workflow_call:
    inputs:
      image:
        type: string
        description: The name of the image to build.
        required: true
      platforms:
        type: string
        description: The OS arches for which to build the docker image.
        default: linux/amd64
        required: false
      tags:
        type: string
        description: Tags for the image.
        required: true
      context:
        type: string
        description: The context for the docker build command.
        required: false
        default: "."
      dockerfile:
        type: string
        description: The path to the dockerfile to build.
        required: true
      build-args:
        type: string
        description: Additional build args to pass to the build command.
        default: ""
        required: false
      dry-run:
        type: boolean
        description: Whether or not to push the image.
        default: false
        required: false
      setup-qemu:
        type: boolean
        description: Whether or not to set up QEMU.
        default: true
        required: false

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up QEMU
        if: ${{ inputs.setup-qemu == true }}
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_RW_TOKEN }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: "${{ inputs.image }}"
          tags: "${{ inputs.tags }}"

      - name: Build and Push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: "${{ inputs.context }}"
          file: "${{ inputs.dockerfile }}"
          platforms: "${{ inputs.platforms }}"
          push: "${{ !inputs.dry-run }}"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          build-args: "${{ inputs.build-args }}"
          cache-to: type=registry,ref=${{ inputs.image }}:buildcache
          cache-from: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
